spring:
  application:
    name: toy-claw-cleaner

  jpa:
    hibernate:
      ddl-auto: create-drop   # ???: create / create-drop / update / validate ? ??
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:toydb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

